chore: husky prepush and precommit

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -5,11 +5,7 @@
 echo "Husky.NET Started"
 echo "Running Pre-Push Hook"
 
-dotnet build
-if [ $? -ne 0 ]; then
-  echo "Build failed. Please fix the errors before pushing."
-  exit 1
-fi
+dotnet build || { echo "Build failed!"; exit 1; }
 
 echo "Husky.NET Finished"
 
